# -*- coding: utf-8 -*-
"""
Created on Mon Oct  1 17:15:31 2018

@author: Pan Xiangyu
"""
import sys
if len(sys.argv) < 3:
    print('Usage: python3.5 '+sys.argv[0]+'[input file1] [output file]')
    exit(1)
infile1 = open(sys.argv[1])
outfile=open(sys.argv[2],'w')
'''
>Cattle.A4GNT
GGCCGGCCGGCCCCGCCATCCGGTCGTTGGACGACAGCCTGATATCTGGTGCCGCACTCACTCCCAATCTGAGGTCGAACCCCTCACCCTGTATGAGGACCTGGACTCATACGCCACCTACGCCGGCCGGGTGCAAGGCTCTTTT
>Cervus_albirostris.A4GNT
GGCCGGCCGGCCCGGCCATCGGGCCGCTGGACGACGGCCTGATATCTGGTGCCGCGCTCACTCCCAGTCTGAGGTCCAACCCCTCACCCTGTATGCGGACCCGGACTCGTACGCCACCTACGCCGGCCCGGTGCAAGGCTCTGTT
>Cervus_elaphus.A4GNT
GGCCGGCCGGCCCCGCCATCGGGCCGCTGGACGACGGCCTGATATCTGGTGCCGCGCTCACTCCCAGTCTGAGGTCCAACCCCTCACCCCGTATGCGGACCCGGACTCGTACGCCACCTACGCCGGCCCGGTGCAAGGCTCTGTT
>Cervus_nippon.A4GNT
GGCCGGCCGGCCCGGCCATCGGGCCGCTGGACGACGGCCTGATATCTGGTGCCGCGCTCACTCCCAGTCTGAGGTCCAACCCCTCACCCTGTATGCGGACCCGGACTCGTACGCCACCTACGCCGGCCCGGTGCAAGGCTCTGTT
>Dama_dama.A4GNT
GGCCGGCCGGCCCCGCCATCGGGCCGCTGGACAACGGCCTGATATCTGGTGCCGCGCTCACGCCCAGTCTGAGGGCCAACCCCTCACCCTGTATGCGGACCCGGACTCGTACGCCATCTACGCCGGCCCGGTGCAAGGCTCTGTT
>Elaphurus_davidianus.A4GNT
GGCCGGCCGGCCCGGCCATCGGGCCGCTGGACGACGGCCTGATATCTGGTGCCGCGCTCACTCCCAGTCTGAGGTCCAACCCCTCACCCTGTATGCGGACCCGGACTCGTACGCCACCTACGCCGGCCCGGTGCAAGGCTCTGTT
>Giraffe.A4GNT
GGCCGGCCGGCCCCGCCATCAGGCTGCTGGACGACAGCCTGATATCTGGTGCCGCACTCACTCCCAATCTGAGGTCCAACCCTTCACCTTGTATGCGGACCTGGACTCGTACGCCAACTACGCCAGCCCGGTGCAAGGCTCTGTT
>Hydropotes_inermis.A4GNT
GGCCGGCCGGCCCCGCCATCCGGCCGCTGGACGACGGCCTGATATCTGATGCCGCGCTCACTCCCAATCTGAGGTCCAGCCCCTCGCCCTGTATGCGGACCCGGACTCGTACGCCACCTACGCCAACCCGGTGCAAGGCTCTTTT
'''
TV = {}
for line in infile1:
    line = line.strip()
    if '>' in line:
        name = line
        TV[name] = ''
    else:
        TV[name] =line
for key,value in TV.items():
    outfile.write(key+"\t"+value+"\n")
